// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wlj-service/wlj.proto
// Protobuf Java Version: 4.26.0

package com.github.paopaoyue.wljmod.proto;

public final class WljProto {
  private WljProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      WljProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code rpc.ServiceStatusCode}
   */
  public enum ServiceStatusCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SERVICE_OK = 0;</code>
     */
    SERVICE_OK(0),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "",
        ServiceStatusCode.class.getName());
    }
    /**
     * <code>SERVICE_OK = 0;</code>
     */
    public static final int SERVICE_OK_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ServiceStatusCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ServiceStatusCode forNumber(int value) {
      switch (value) {
        case 0: return SERVICE_OK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ServiceStatusCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ServiceStatusCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ServiceStatusCode>() {
            public ServiceStatusCode findValueByNumber(int number) {
              return ServiceStatusCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.paopaoyue.wljmod.proto.WljProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ServiceStatusCode[] VALUES = values();

    public static ServiceStatusCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ServiceStatusCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:rpc.ServiceStatusCode)
  }

  public interface EchoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.EchoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * <pre>
   * ############################
   * should define your proto objects here:
   * </pre>
   *
   * Protobuf type {@code rpc.EchoRequest}
   */
  public static final class EchoRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rpc.EchoRequest)
      EchoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "",
        EchoRequest.class.getName());
    }
    // Use EchoRequest.newBuilder() to construct.
    private EchoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EchoRequest() {
      text_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.paopaoyue.wljmod.proto.WljProto.internal_static_rpc_EchoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.paopaoyue.wljmod.proto.WljProto.internal_static_rpc_EchoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest.class, com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest.Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object text_ = "";
    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, text_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, text_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest)) {
        return super.equals(obj);
      }
      com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest other = (com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest) obj;

      if (!getText()
          .equals(other.getText())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ############################
     * should define your proto objects here:
     * </pre>
     *
     * Protobuf type {@code rpc.EchoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.EchoRequest)
        com.github.paopaoyue.wljmod.proto.WljProto.EchoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.paopaoyue.wljmod.proto.WljProto.internal_static_rpc_EchoRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.paopaoyue.wljmod.proto.WljProto.internal_static_rpc_EchoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest.class, com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest.Builder.class);
      }

      // Construct using com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        text_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.paopaoyue.wljmod.proto.WljProto.internal_static_rpc_EchoRequest_descriptor;
      }

      @java.lang.Override
      public com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest getDefaultInstanceForType() {
        return com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest build() {
        com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest buildPartial() {
        com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest result = new com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.text_ = text_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest) {
          return mergeFrom((com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest other) {
        if (other == com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                text_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 1;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        text_ = getDefaultInstance().getText();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rpc.EchoRequest)
    }

    // @@protoc_insertion_point(class_scope:rpc.EchoRequest)
    private static final com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest();
    }

    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EchoRequest>
        PARSER = new com.google.protobuf.AbstractParser<EchoRequest>() {
      @java.lang.Override
      public EchoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EchoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EchoRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.paopaoyue.wljmod.proto.WljProto.EchoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EchoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.EchoResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <pre>
     * should always include this field in response object
     * </pre>
     *
     * <code>.rpc.RespBase base = 255;</code>
     * @return Whether the base field is set.
     */
    boolean hasBase();
    /**
     * <pre>
     * should always include this field in response object
     * </pre>
     *
     * <code>.rpc.RespBase base = 255;</code>
     * @return The base.
     */
    io.github.paopaoyue.mesh.rpc.proto.Base.RespBase getBase();
    /**
     * <pre>
     * should always include this field in response object
     * </pre>
     *
     * <code>.rpc.RespBase base = 255;</code>
     */
    io.github.paopaoyue.mesh.rpc.proto.Base.RespBaseOrBuilder getBaseOrBuilder();
  }
  /**
   * Protobuf type {@code rpc.EchoResponse}
   */
  public static final class EchoResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rpc.EchoResponse)
      EchoResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "",
        EchoResponse.class.getName());
    }
    // Use EchoResponse.newBuilder() to construct.
    private EchoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private EchoResponse() {
      text_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.paopaoyue.wljmod.proto.WljProto.internal_static_rpc_EchoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.paopaoyue.wljmod.proto.WljProto.internal_static_rpc_EchoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse.class, com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse.Builder.class);
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object text_ = "";
    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASE_FIELD_NUMBER = 255;
    private io.github.paopaoyue.mesh.rpc.proto.Base.RespBase base_;
    /**
     * <pre>
     * should always include this field in response object
     * </pre>
     *
     * <code>.rpc.RespBase base = 255;</code>
     * @return Whether the base field is set.
     */
    @java.lang.Override
    public boolean hasBase() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * should always include this field in response object
     * </pre>
     *
     * <code>.rpc.RespBase base = 255;</code>
     * @return The base.
     */
    @java.lang.Override
    public io.github.paopaoyue.mesh.rpc.proto.Base.RespBase getBase() {
      return base_ == null ? io.github.paopaoyue.mesh.rpc.proto.Base.RespBase.getDefaultInstance() : base_;
    }
    /**
     * <pre>
     * should always include this field in response object
     * </pre>
     *
     * <code>.rpc.RespBase base = 255;</code>
     */
    @java.lang.Override
    public io.github.paopaoyue.mesh.rpc.proto.Base.RespBaseOrBuilder getBaseOrBuilder() {
      return base_ == null ? io.github.paopaoyue.mesh.rpc.proto.Base.RespBase.getDefaultInstance() : base_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, text_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(255, getBase());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, text_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(255, getBase());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse)) {
        return super.equals(obj);
      }
      com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse other = (com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse) obj;

      if (!getText()
          .equals(other.getText())) return false;
      if (hasBase() != other.hasBase()) return false;
      if (hasBase()) {
        if (!getBase()
            .equals(other.getBase())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      if (hasBase()) {
        hash = (37 * hash) + BASE_FIELD_NUMBER;
        hash = (53 * hash) + getBase().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rpc.EchoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.EchoResponse)
        com.github.paopaoyue.wljmod.proto.WljProto.EchoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.paopaoyue.wljmod.proto.WljProto.internal_static_rpc_EchoResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.paopaoyue.wljmod.proto.WljProto.internal_static_rpc_EchoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse.class, com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse.Builder.class);
      }

      // Construct using com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getBaseFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        text_ = "";
        base_ = null;
        if (baseBuilder_ != null) {
          baseBuilder_.dispose();
          baseBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.paopaoyue.wljmod.proto.WljProto.internal_static_rpc_EchoResponse_descriptor;
      }

      @java.lang.Override
      public com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse getDefaultInstanceForType() {
        return com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse build() {
        com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse buildPartial() {
        com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse result = new com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.text_ = text_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.base_ = baseBuilder_ == null
              ? base_
              : baseBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse) {
          return mergeFrom((com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse other) {
        if (other == com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasBase()) {
          mergeBase(other.getBase());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                text_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 2042: {
                input.readMessage(
                    getBaseFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 2042
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 1;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        text_ = getDefaultInstance().getText();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        text_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private io.github.paopaoyue.mesh.rpc.proto.Base.RespBase base_;
      private com.google.protobuf.SingleFieldBuilder<
          io.github.paopaoyue.mesh.rpc.proto.Base.RespBase, io.github.paopaoyue.mesh.rpc.proto.Base.RespBase.Builder, io.github.paopaoyue.mesh.rpc.proto.Base.RespBaseOrBuilder> baseBuilder_;
      /**
       * <pre>
       * should always include this field in response object
       * </pre>
       *
       * <code>.rpc.RespBase base = 255;</code>
       * @return Whether the base field is set.
       */
      public boolean hasBase() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * should always include this field in response object
       * </pre>
       *
       * <code>.rpc.RespBase base = 255;</code>
       * @return The base.
       */
      public io.github.paopaoyue.mesh.rpc.proto.Base.RespBase getBase() {
        if (baseBuilder_ == null) {
          return base_ == null ? io.github.paopaoyue.mesh.rpc.proto.Base.RespBase.getDefaultInstance() : base_;
        } else {
          return baseBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * should always include this field in response object
       * </pre>
       *
       * <code>.rpc.RespBase base = 255;</code>
       */
      public Builder setBase(io.github.paopaoyue.mesh.rpc.proto.Base.RespBase value) {
        if (baseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          base_ = value;
        } else {
          baseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * should always include this field in response object
       * </pre>
       *
       * <code>.rpc.RespBase base = 255;</code>
       */
      public Builder setBase(
          io.github.paopaoyue.mesh.rpc.proto.Base.RespBase.Builder builderForValue) {
        if (baseBuilder_ == null) {
          base_ = builderForValue.build();
        } else {
          baseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * should always include this field in response object
       * </pre>
       *
       * <code>.rpc.RespBase base = 255;</code>
       */
      public Builder mergeBase(io.github.paopaoyue.mesh.rpc.proto.Base.RespBase value) {
        if (baseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            base_ != null &&
            base_ != io.github.paopaoyue.mesh.rpc.proto.Base.RespBase.getDefaultInstance()) {
            getBaseBuilder().mergeFrom(value);
          } else {
            base_ = value;
          }
        } else {
          baseBuilder_.mergeFrom(value);
        }
        if (base_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * should always include this field in response object
       * </pre>
       *
       * <code>.rpc.RespBase base = 255;</code>
       */
      public Builder clearBase() {
        bitField0_ = (bitField0_ & ~0x00000002);
        base_ = null;
        if (baseBuilder_ != null) {
          baseBuilder_.dispose();
          baseBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * should always include this field in response object
       * </pre>
       *
       * <code>.rpc.RespBase base = 255;</code>
       */
      public io.github.paopaoyue.mesh.rpc.proto.Base.RespBase.Builder getBaseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBaseFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * should always include this field in response object
       * </pre>
       *
       * <code>.rpc.RespBase base = 255;</code>
       */
      public io.github.paopaoyue.mesh.rpc.proto.Base.RespBaseOrBuilder getBaseOrBuilder() {
        if (baseBuilder_ != null) {
          return baseBuilder_.getMessageOrBuilder();
        } else {
          return base_ == null ?
              io.github.paopaoyue.mesh.rpc.proto.Base.RespBase.getDefaultInstance() : base_;
        }
      }
      /**
       * <pre>
       * should always include this field in response object
       * </pre>
       *
       * <code>.rpc.RespBase base = 255;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          io.github.paopaoyue.mesh.rpc.proto.Base.RespBase, io.github.paopaoyue.mesh.rpc.proto.Base.RespBase.Builder, io.github.paopaoyue.mesh.rpc.proto.Base.RespBaseOrBuilder> 
          getBaseFieldBuilder() {
        if (baseBuilder_ == null) {
          baseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              io.github.paopaoyue.mesh.rpc.proto.Base.RespBase, io.github.paopaoyue.mesh.rpc.proto.Base.RespBase.Builder, io.github.paopaoyue.mesh.rpc.proto.Base.RespBaseOrBuilder>(
                  getBase(),
                  getParentForChildren(),
                  isClean());
          base_ = null;
        }
        return baseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:rpc.EchoResponse)
    }

    // @@protoc_insertion_point(class_scope:rpc.EchoResponse)
    private static final com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse();
    }

    public static com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EchoResponse>
        PARSER = new com.google.protobuf.AbstractParser<EchoResponse>() {
      @java.lang.Override
      public EchoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EchoResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EchoResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.paopaoyue.wljmod.proto.WljProto.EchoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_EchoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_EchoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_EchoResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_EchoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025wlj-service/wlj.proto\022\003rpc\032\nbase.proto" +
      "\"\033\n\013EchoRequest\022\014\n\004text\030\001 \001(\t\":\n\014EchoRes" +
      "ponse\022\014\n\004text\030\001 \001(\t\022\034\n\004base\030\377\001 \001(\0132\r.rpc" +
      ".RespBase*#\n\021ServiceStatusCode\022\016\n\nSERVIC" +
      "E_OK\020\00022\n\003Wlj\022+\n\004echo\022\020.rpc.EchoRequest\032" +
      "\021.rpc.EchoResponseB-\n!com.github.paopaoy" +
      "ue.wljmod.protoB\010WljProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.github.paopaoyue.mesh.rpc.proto.Base.getDescriptor(),
        });
    internal_static_rpc_EchoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_EchoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rpc_EchoRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_rpc_EchoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpc_EchoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rpc_EchoResponse_descriptor,
        new java.lang.String[] { "Text", "Base", });
    descriptor.resolveAllFeaturesImmutable();
    io.github.paopaoyue.mesh.rpc.proto.Base.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
